from typing import Any

from pydantic import BaseModel, Field


class ChatMessage(BaseModel):
    role: str = Field(..., description="Message role such as user or assistant")
    content: str = Field(..., description="Message content")


class ChatRequest(BaseModel):
    question: str = Field(..., min_length=1, description="The user's question")
    analysis: dict[str, Any] = Field(..., description="The repository analysis context already produced by Atlas")
    conversation: list[ChatMessage] | None = Field(
        default=None,
        description="Optional prior conversation history for follow-up questions",
    )


class ChatSource(BaseModel):
    title: str = Field(..., description="Short label for the source evidence")
    kind: str = Field(..., description="Category such as summary, architecture, structure, tech_stack")
    snippet: str = Field(..., description="Relevant evidence excerpt")


class ChatResponse(BaseModel):
    answer: str = Field(..., description="Repository-aware answer generated by the assistant")
    sources: list[ChatSource] = Field(default_factory=list, description="Evidence sources used to support the answer")
